import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="fantasy">
      <body>
        {/* <Theme> */}
        <header>
          <Navbar></Navbar>
        </header>
        <main> {children}</main>
        {/* </Theme> */}
      </body>
    </html>
  );
}
